In [9]:
import requests
import json
import pandas as pd
import numpy as np

In [15]:

sample = "pump_evx_20211024_binance__simplified"      # enter pairs you are looking for
path = "C:\\Users\\Ahmet\\Desktop\\Uni\\TechLab\\Scam Busters\\Samples\\financial_data\\" # the path to your folder with the data

df = pd.read_csv(path + sample + '.csv')    # reads the csv

print(df)

      Unnamed: 0      open_time    open    high     low   close  volume  \
0              0  1634733060000  1047.0  1047.0  1047.0  1047.0     0.0
1              1  1634733120000  1047.0  1047.0  1047.0  1047.0     0.0
2              2  1634733180000  1047.0  1047.0  1047.0  1047.0     0.0
3              3  1634733240000  1047.0  1047.0  1047.0  1047.0     0.0
4              4  1634733300000  1047.0  1047.0  1047.0  1047.0     0.0
...          ...            ...     ...     ...     ...     ...     ...
5995        5995  1635092760000  1163.0  1163.0  1163.0  1163.0   124.0
5996        5996  1635092820000  1165.0  1166.0  1163.0  1163.0  2614.0
5997        5997  1635092880000  1168.0  1169.0  1161.0  1161.0  2770.0
5998        5998  1635092940000  1169.0  1169.0  1169.0  1169.0   284.0
5999        5999  1635093000000  1161.0  1161.0  1155.0  1155.0   774.0

         close_time  quote_asset_volume  n_trades  \
0     1634733119999            0.000000         0
1     1634733179999            0.000000         0
2     1634733239999            0.000000         0
3     1634733299999            0.000000         0
4     1634733359999            0.000000         0
...             ...                 ...       ...
5995  1635092819999            0.001442        14
5996  1635092879999            0.030417        12
5997  1635092939999            0.032219        12
5998  1635092999999            0.003320         1
5999  1635093059999            0.008971        10

      taker_buy_base_asset_volume  taker_buy_quote_asset_volume pairing
0                             0.0                      0.000000  EVXBTC
1                             0.0                      0.000000  EVXBTC
2                             0.0                      0.000000  EVXBTC
3                             0.0                      0.000000  EVXBTC
4                             0.0                      0.000000  EVXBTC
...                           ...                           ...     ...
5995                        124.0                      0.001442  EVXBTC
5996                        315.0                      0.003670  EVXBTC
5997                        266.0                      0.003107  EVXBTC
5998                        284.0                      0.003320  EVXBTC
5999                          0.0                      0.000000  EVXBTC

[6000 rows x 13 columns]

In [ ]:
# df.time =[
#     pd.to_datetime(ts, unit='ms')
#     for ts 
#     in df.time
# ]

# changes the time to other format (can take a minute to calculate)
df.open_time.apply(lambda x : pd.to_datetime(x, unit="ms"))
print(df)

In [14]:
print(df.shape)

(6000, 13)