In [3]:
import requests
import json
import pandas as pd

In [4]:
pair_list = pd.read_csv(r"C:\Users\Ahmet\Desktop\Uni\TechLab\Scam Busters\History_Data_Crypto\Kaggle\rename.csv", 
                        header=1, delimiter=";").iloc[:,1]

pair_name = ("zrx", "usd")
path = "C:/Users/Ahmet/Desktop/Uni/TechLab/Scam Busters/History_Data_Crypto/Kaggle/" 

df = pd.read_csv(path + pair_name[0] + pair_name[1]+ '.csv')
df['Pair']=pair_name[0] +" to "+ pair_name[1]

In [6]:
# df.time =[
#     pd.to_datetime(ts, unit='ms')
#     for ts 
#     in df.time
# ]
df.time.apply(lambda x:pd.to_datetime(x, unit="ms"))

In [ ]:
coin_name = "gp_eth"

for coin_name in response['pairs']:
  print(coin_name)

data_eth = pandas.DataFrame(response['pairs'][coin_name], index=[1])

In [26]:
data_eth["time"] = response["server_time"]
data_eth["coin_name"] = coin_name

In [ ]:
column_to_move = data_eth.pop("time")

# insert column with insert(location, column_name, column_value)

data_eth.insert(0, "time", column_to_move)

In [ ]:
response['pairs']

In [9]:
response = requests.get("https://yobit.net/api/3/info").json()
pairings = response['pairs']
pairings_df = pandas.DataFrame.from_dict(pairings)
pairings_list = pairings_df.columns

In [10]:
response_list = []
for pairing in pairings_list[0:50]: 
    if 'btc' in pairing:
        # daten von api
        response = requests.get('https://yobit.net/api/3/trades/'+pairing).json()

        try:
            # strukturieren
            df = pandas.DataFrame(response.get(pairing))
        # bei fehlern einfach überspringen
        except AttributeError:
            continue
        df['pairing'] = pairing
        # sammeln
        response_list.append(df)
data_complete = pandas.concat(response_list)
data_complete.reset_index(inplace=True,drop=True)

In [16]:
data_complete[:152]

    type     price      amount        tid   timestamp  pairing
0    bid  0.002940    0.244374  202467423  1643544639  ltc_btc
1    bid  0.002940    0.251953  202467422  1643544637  ltc_btc
2    bid  0.002940    0.254556  202467421  1643544637  ltc_btc
3    bid  0.002940    0.042203  202467420  1643544595  ltc_btc
4    bid  0.002937  405.777600  202467419  1643544482  ltc_btc
..   ...       ...         ...        ...         ...      ...
147  bid  0.002917   65.610000  202467275  1643519804  ltc_btc
148  bid  0.002915   98.010000  202467274  1643519487  ltc_btc
149  bid  0.002919   84.726000  202467273  1643519168  ltc_btc
150  ask  0.000011   14.820931  200034039  1643206068  nmc_btc
151  ask  0.000015   92.982795  200034038  1643180063  nmc_btc

[152 rows x 6 columns]